apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-tomcat-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/d2krish/argocd.git'
    path: manifests
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true #if you want to create ns 
    automated:
      selfHeal: true
      prune: true
