apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tomcat-app-deployment
  labels:
    app: my-tomcat-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-tomcat-app
  template:
    metadata:
      labels:
        app: my-tomcat-app
    spec:
      containers:
      - name: argocd-deployment
        image: d2krish/my-tomcat-app:0.0.1
        ports:
        - containerPort: 8080
